name: Mener une vie moderne tout en vivant l'Évangile
author: Pascal Laliberté
url: http://par.pascallaliberte.me
lang: fr
alt_lang: en
alt_lang_url: http://by.pascallaliberte.me
markdown: kramdown
highlighter: true
permalink: /:categories/:year-:month-:title/
paginate: 5
paginate_path: "page:num"
excerpt_separator: "<!-- MORE -->"
baseurl:
port: 4001
gems:
  - jekyll-sitemap
exclude:
  - a/bower_components/jquery.smooth-scroll/index.html
  - a/bower_components/swipebox/index.html
